service: ang-chat-sls

plugins:
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 10
  stage: dev
  region: eu-west-2

package:
  exclude:
   - src/**
   - node_modules/**
   - '!node_modules/aws-serverless-express/**'
   - '!node_modules/binary-case/**'

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  api:
    handler: lambda.universal
    events:
      - http: ANY {proxy+}
      - http: ANY /